### ISSUE TITLE
Not able to run the modpack due to java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by SilverHatTrick** [supermassimo/DynamicTeesPlus#7]
Using the latest version of Dynamic Trees and Dynamic + available on Curseforge. 

https://pastebin.com/H7DmAaWe

**Comment by DillonSimeone** [comment]
Same issue here.

https://pastebin.com/z6WRLF3s

Everything was working for me yesterday, I only updated Dynamic Trees Plus today. Rolling back to previous version now.

**Comment by Harleyoc1** [comment]
You are running beta 6 of DT+, latest is beta 10. Make sure to keep both up to date as DT+ will often require changes from DT to work or will require changes to work with DT (mainly due to them both being in beta, shouldn't be a problem once we do a full release for both and avoid making breaking changes).
